require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Rails/FilePath:
  EnforcedStyle: arguments

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 15

Rails/ActiveRecordOverride:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false